### ISSUE TITLE
After merging the Qwen model, the model failed to load due to missing files

### ISSUE THREAD

**Issue by ArcherShirou** [cg123/mergekit#105]
Excuse me, I have a few questions to ask,and I am loking forward to your answer:
I use passthrough and slerp to merge qwen14B, here is my passthrough yaml:
```yaml
slices:
  - sources:
    - model: /mnt/Qwen-14B-Chat
      layer_range: [0, 39]
  - sources:
    - model: /mnt/Qwen-14B-Chat
      layer_range: [31, 39]
merge_method: passthrough
dtype: bfloat16
```
and slerp yaml:
```yaml
slices:
  - sources:
      - model: /mnt/Qwen-14B-Chat
        layer_range: [0, 32]
      - model: /mnt/Qwen-14B-Chat
        layer_range: [0, 32]
merge_method: slerp
base_model: /mnt/Qwen-14B-Chat
parameters:
  t:
    - filter: self_attn
      value: [0, 0.5, 0.3, 0.7, 1]
    - filter: mlp
      value: [1, 0.5, 0.7, 0.3, 0]
    - value: 0.5
dtype: bfloat16
```
I run follow command and give me a hint: merge model is also succeed but need copy tokenizer from another place:
```command
mergekit-yaml /mnt/merge.yaml /mnt/qwen_merge --trust-remote-code --cuda 
```
Now I copy from Qwen14B,：
```python
tokenizer = AutoTokenizer.from_pretrained(token_path, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_path, device_map='auto', trust_remote_code=True)
tokenizer.save_pretrained(model_path)
```
but the error occur ,it tells me I lost three file in merge model file:
```python
OSError: /mnt/qwen_merge does not appear to have a file named modeling_qwen.py(cpp_kernels.py,qwen_generation_utils.py) . Checkout 'https://huggingface.co//mnt/qwen_merge/None' for available files.
```
Should I copy three files from original Qwen14B？
If I copy these files and tokenizer from Qwen14B and test the model, I will find that the model will repeat a certain word to the maximum length。Does this mean I need to fine-tune the model again?
The last question is：If I want to combine two different models, both of which have their own input prompt format, which model's input format should be used for the merged model?
Thanks
