### ISSUE TITLE
What is the density for TIES when using DARE by setting `merge_method: dare_ties`?

### ISSUE THREAD

**Issue by syGOAT** [cg123/mergekit#130]
Congratulations on the significant breakthrough achieved in model merging! I'd like to ask you a question. 
I use `dare_ties` to merge some models. Here is my yaml file:
```yaml
models:
  - model: mistralai/Mistral-7B-v0.1
    # No parameters necessary for base model
  - model: samir-fama/SamirGPT-v1
    parameters:
      density: 0.53
      weight: 0.4
  - model: abacusai/Slerp-CM-mist-dpo
    parameters:
      density: 0.53
      weight: 0.3
  - model: EmbeddedLLM/Mistral-7B-Merge-14-v0.2
    parameters:
      density: 0.53
      weight: 0.3
merge_method: dare_ties
base_model: mistralai/Mistral-7B-v0.1
parameters:
  int8_mask: true
dtype: bfloat16
```
I believe the 'density' here refers to the delta parameters randomly retained by DARE. What is the density during the TIES stage after using DARE? Is it the same as the density of DARE, or is there a specific method for setting it?
