### ISSUE TITLE
Mangled results when merging two 7B models into a smaller model

### ISSUE THREAD

**Issue by fakerybakery** [cg123/mergekit#24]
Hi,
I'm using this config
```yaml
slices:
  - sources:
    - model: HuggingFaceH4/zephyr-7b-beta
      layer_range: [0, 12]
  - sources:
    - model: argilla/notus-7b-v1
      layer_range: [28, 32]
merge_method: passthrough
dtype: bfloat16
```
And when I run this code:
```python
from transformers import pipeline
import torch
pipe = pipeline('text-generation', model='minihermes', device='mps')
pipe('Python is a programming language')
```
I get:
```python
[{'generated_text': 'Python is a programming language, <a\n luego without.\n\n\n\n\n\n\n\n'}]
```
I feel like I'm doing something wrong here... Is this an issue w/ the tokenizer?
