### ISSUE TITLE
DARE: Separate base models for delta measurement and merge?

### ISSUE THREAD

**Issue by discordianbelle** [cg123/mergekit#25]
I have a request. If I understand correctly, the DARE merge measures the deltas from the base model given in the YML to the other models in the merge, then uses those deltas to do the whole "Mario merge" thing.

However, I want to merge a model finetuned on vanilla Llama 2 into a model trained over sequelbox/DynamicFactor (a model intended as an improved base for further finetuning.)

Is it possible for you to add a feature that allows us to use one base model during the delta measurements (in my case vanilla L2) and then another model during the merge itself (in my case DynamicFactor)?

**Comment by cg123** [comment]
This is totally possible. I'll look into how to add this. I'll need to think a bit on how to do it without complicating things too much though.

In the meanwhile, if you're flush with disk space then you can get the same end result by doing an additional merge at the end. The `task_arithmetic` method is simply adding deltas, like DARE or TIES but without any sparsification or other processing. Say you've merged some models using Llama-2-13B as a base, but you want DynamicFactor as the "base" of the final merge. In this case you can just add the difference between DynamicFactor and Llama-2, like so:
```yml
merge_method: task_arithmetic
base_model: TheBloke/Llama-2-13B-fp16
models:
  - model: your_merge  # your merge run with llama-2 as the base goes here
  - model: sequelbox/DynamicFactor
parameters:
  weight: 1.0
dtype: float16
```

Or if I'm misinterpreting and you want to do a different merge, like llama + (model_a - llama) + (model_b - dynamicfactor), then you can make a really dumb intermediate model like this:
```yml
merge_method: task_arithmetic
base_model: model_b
models:
  - model: TheBloke/Llama-2-13B-fp16
    parameters:
      weight: 1.0
  - model: sequelbox/DynamicFactor
    parameters:
      weight: -1.0  # >:)
```
That'll give you `model_b + (Llama-2-13B-fp16 - DynamicFactor)`, so measuring the deltas of this against Llama2 will give you the same result as measuring the delta of model_b against DynamicFactor. Then you can use it in a merge with Llama-2 as the base. Not sure how well this type of merge would work in general though.

Hope this helps, and thanks for your interest in the project!
