### ISSUE TITLE
Can I perform a task_arithmetic or TIES merge on two embedding matrices?

### ISSUE THREAD

**Issue by shamanez** [cg123/mergekit#27]
@cg123  Thanks a lot for the amazing work :) 

I want to update the embedding matrix of the base model with a delta embedding matrix from another task-specific model. 

I intend to focus solely on the embedding layer. Is there a specific method for doing this?

**Comment by cg123** [comment]
Thank you - glad it's being used!

I actually don't have a great way of doing this right now. At the moment the embedding and language model weights come along for the ride with the first and last slices, respectively. If you're okay with a single layer being merged as well then you can do something like this:

```yml
slices:
  - sources:
      - model: model_a
        layer_range: [0, 1]
        # parameters with weight etc.
      - model: model_b
        layer_range: [0, 1]
        # and parameters again
  - sources:
      - model: model_b
        layer_range: [1, n_layers]
merge_method: task_arithmetic
```

I suspect that doesn't work for you though - and that's a totally valid use case that I just didn't think of.

I'll work on a way to call out the embedding (and language model head) separately for this kind of merge. Thanks for pointing out the issue.

**Comment by cg123** [comment]
Actually, come to think of it, you can probably abuse a gradient to do what you want. The embedding always has t=0 and single-layer slices will give t=1 for the actual layer parameters. So maybe try something like this:

```yml
slices:
  - sources:
      - model: model_a
        layer_range: [0, 1]
        parameters:
          weight: [0.15, 0]
  - sources:
      - model: model_base
        layer_range: [1, n_layers]
base_model: model_base
merge_method: task_arithmetic
```

This *should* give you `model_base` but with 15% of the delta (model_a-model_base) added to the embedding only.
Even if that does work it's quite silly and I'll work on a better way to do this kind of thing regardless.

**Comment by cg123** [comment]
Actually, whoops I'm dumb. You can do this super easily using parameter filters. Try this:
```
models:
  - model: model_a
    parameters:
      weight:
        - filter: embed_tokens # or the name of your embedding if not llama
          value: 0.15
        - value: 0
  - model: model_base
base_model: model_base
merge_method: task_arithmetic
```

That sets the `weight` parameter to 0.15 for tensors including `embed_tokens` in the name and 0 for all others.
