### ISSUE TITLE
No rule to produce...

### ISSUE THREAD

**Issue by theblackmallard** [cg123/mergekit#29]
Hello,

I'm using the notebook.ipynb for starters with some slight modifications.

I've tried these two different YAMLs below and am getting two different, though similar, errors. `allow_crimes=True` and the models seem to download just fine.

### First: passthrough
```yaml
slices:
  - sources:
    - model: stabilityai/stablelm-zephyr-3b
      layer_range: [0, 16]
  - sources:
    - model: stabilityai/stablecode-instruct-alpha-3b
      layer_range: [16, 32]
merge_method: passthrough
dtype: float16
```
When called like this
```python
mergekit.scripts.run_yaml.main(
    CONFIG_YML,
    OUTPUT_PATH,
    LORA_MERGE_CACHE,
    cuda=torch.cuda.is_available(),
    copy_tokenizer=COPY_TOKENIZER,
    lazy_unpickle=LAZY_UNPICKLE,
    low_cpu_memory=LOW_CPU_MEMORY,
    trust_remote_code=True,
    allow_crimes=True
)
```

This yields an error
`No rule to produce stabilityai/stablecode-instruct-alpha-3b:model.layers.16.input_layernorm.weight`

or when run like this
`!mergekit-yaml /content/passthrough.yml /content/ --cuda --allow-crimes --trust-remote-code`
I receive this error
`RuntimeError: No rule to produce stabilityai/stablelm-zephyr-3b:gpt_neox.embed_in.weight`

---

### Second: linear
While this setup
```yaml
models:
  - model: stabilityai/stablelm-zephyr-3b
    parameters:
      weight: 1.0
      normalize: true
  - model: stabilityai/stablecode-instruct-alpha-3b
    parameters:
      weight: 0.3
      normalize: true
merge_method: linear
dtype: float16
```
Called via the same python code above as well as the CLI method, it yields this error
`RuntimeError: No rule to produce stabilityai/stablecode-instruct-alpha-3b:model.embed_tokens.weight`

---
### Additional Notes
There was another error, but I forgot the YAML file used to create it.
`No rule to produce stabilityai/stablelm-zephyr-3b:gpt_neox.embed_in.weight`

The `trust_remote_code=True` and `--trust-remote-code` don't appear to do anything, I'm still prompted `y/N` just the same as without it.

Thanks for any help!
