### ISSUE TITLE
I was wondering after merging did I need fine-tune the merged model?

### ISSUE THREAD

**Issue by zyh3826** [cg123/mergekit#3]
Nice job
I have a question, after merging did I need to fine-tune the merged model?

**Comment by cg123** [comment]
Thanks!

No, the merged model should be usable as is. You certainly can fine tune it if you want, but in general most people will directly use the merged model.

**Comment by zyh3826** [comment]
> Thanks!
> 
> No, the merged model should be usable as is. You certainly can fine tune it if you want, but in general most people will directly use the merged model.

thanks for your rely

**Comment by zyh3826** [comment]
when using `ties` method, I got an error
![image](https://github.com/cg123/mergekit/assets/31238754/e46ff652-b303-4e40-a3e2-3a5b37ea949a)
my yaml config like this:
![image](https://github.com/cg123/mergekit/assets/31238754/4481925e-4329-4d6c-bfa5-60af211dc22b)
can you help me, please.
thanks

**Comment by cg123** [comment]
This error comes from the fact that your base model needed to be specified both in the `base_model` field and in the `models` list. As an example, with hypothetical models stored in `/workspace`:
```yaml
models:
  - model: /workspace/base_model
  - model: /workspace/model_a
    parameters:
      weight: 0.3
      density: 0.5
  - model: /workspace/model_b
    parameters:
      weight: 0.5
      density: 0.5
base_model: /workspace/base_model
merge_method: ties
dtype: float16
```

I know that's very silly and unintuitive. As of f7bcfbc9ada29f97777e835497ac6aa365ecf1ba this is no longer the case, so the config you posted there should work without modification. Let me know if you have any more trouble with it!
