### ISSUE TITLE
Can you conduct TIES merging only on the embedding weights of two models?

### ISSUE THREAD

**Issue by shamanez** [cg123/mergekit#44]

**Comment by cg123** [comment]
Sorry for not getting to this sooner!

You can definitely do this. You just need to consider what you want to use as a base model and be careful about setting densities.

If you have two Mistral-based models, for example, and what you want is the result of a standard TIES merge for `embed_tokens` but just `your_model_a` everywhere else, you can do this:
```yml
merge_method: ties
base_model: mistralai/Mistral-7B-v0.1
models:
  - model: your_model_a
    parameters:
      weight: 0.7 # weighting is relative by default so no need to set different weights for different tensors
      density:
        - filter: embed_tokens # keep these two lines if you want to sparsify your_model_a's task vector
          value: 0.66          # (as in a typical TIES merge) or remove to only sparsify your_model_b
        - value: 1.0
  - model: your_model_b
    parameters:
      weight: # assign a non-zero weight only to embed_tokens
        - filter: embed_tokens
          value: 0.3 # for example
        - value: 0.0 # and zero everywhere else
      density: 0.66
```

If `your_model_b` is fine tuned off of `your_model_a`, you can do a slightly simpler, weirder merge:
```yml
merge_method: ties
base_model: your_model_a
models:
  - model: your_model_b
    parameters:
      weight:
        - filter: embed_tokens
          value: 0.3
        - value: 0.0
      density: 0.66
parameters:
  normalize: false
```

That will apply a sparsified difference between `model_b.embed_tokens` and `model_a.embed_tokens` at an absolute weight of 0.3.
