### ISSUE TITLE
what is `filter` and `gradient` doing?

### ISSUE THREAD

**Issue by YooSungHyun** [cg123/mergekit#5]
``` yaml
models:
  - model: TheBloke/Llama-2-13B-fp16
    # no parameters necessary for base model
  - model: psmathur/orca_mini_v3_13b
    parameters:
      density: [1, 0.7, 0.1] # density gradient
      weight: 1.0
  - model: garage-bAInd/Platypus2-13B
    parameters:
      density: 0.5
      weight: [0, 0.3, 0.7, 1] # weight gradient
  - model: WizardLM/WizardMath-13B-V1.0
    parameters:
      density: 0.33
      weight:
        - filter: mlp
          value: 0.5
        - value: 0
merge_method: ties
base_model: TheBloke/Llama-2-13B-fp16
parameters:
  normalize: true
  int8_mask: true
dtype: float16
```

Question 1
what is `gradient` doing?
for example, `density` is need to float, but list. and list value is `gradient`
what is gradient? does it generate a result for each value?

Question 2
what is `filter` doing?
does it combine only those, or does it exclude those?
and what is `value`? and one value has '-' but another one is not. what is diffrent between those?

please help~~~!!!

**Comment by cg123** [comment]
`gradient` lets you set a value for a parameter that varies per layer. For a simple example:
```yaml
models:
  - model: TheBloke/Llama-2-13B-fp16
  - model: garage-bAInd/Platypus2-13B
    parameters:
      weight: [0,1]
```
This will make `weight` interpolate from 0 to 1, so the first layer will use weight=0, the halfway point (20th layer for 13b) will use weight=0.5, and the last will use weight=1. 

For the `filter` question, it might be easier to look at the equivalent JSON instead of yaml:
```json
{
  "weight": [
    {
      "filter": "mlp",
      "value": 0.5
    },
    {
      "value": 0
    }
  ]
}
```

Here there is a list of two different "rules" for `weight` and mergekit will choose the first one that matches. The first has a filter of "mlp", so it will only be applied to tensors with names that contain the string "mlp". The second has no filter so will apply to everything else.

Hope this helps!
