### ISSUE TITLE
Runtime Error, please help

### ISSUE THREAD

**Issue by TuyulBrutal** [cg123/mergekit#51]
Please help me, I'm a beginner trying to merge two 7b models using gradient slerp, and I encountered this error.
RuntimeError: No rule to produce (model name):model.layers.32.input_layernorm.weight

**Comment by dillfrescott** [comment]
You are trying to set a layer range that contains layers that the model doesnt have, any number higher than 32 for the second number will cause an error

**Comment by cg123** [comment]
Exactly as @dillfrescott says - 7b models only have 32 layers and I'd bet you're using the example config that specifies 40. You can make it work by either changing the layer ranges to end at 32, or using the `models` syntax instead like so:

```yml
models:
  - model: model_a
  - model: model_b
merge_method: slerp
base_model: model_a
parameters:
  t: # ... and so forth, the same as your current config
```

Sorry for the unintuitive error message!
