### ISSUE TITLE
Could you please explain how passthrough slicing works?

### ISSUE THREAD

**Issue by dillfrescott** [cg123/mergekit#53]
If I have:

```
slices:
  - sources:
    - model: mistralai/Mistral-7B-Instruct-v0.2
      layer_range: [0, 24]
  - sources:
    - model: mistralai/Mistral-7B-Instruct-v0.2
      layer_range: [8, 32]
merge_method: passthrough
dtype: float16
```

Its taking layers 0-24 and then on top its putting layers 8-32 of the same model?

Or does it intermingle them somehow?
