### ISSUE TITLE
Convert Mistral -> Llama

### ISSUE THREAD

**Issue by fakerybakery** [cg123/mergekit#60]
Hi,
Not sure if this is the right place to ask but do you know if it's possible to convert a Mistral model into the Llama format?
Thank you!

**Comment by cg123** [comment]
It's actually super easy to convert a Mistral model into a Llama model. The tensors all have the same names, so all you need to do is edit `config.json`.

There are three things you need to change:
1. Replace "MistralForCausalLM" with "LlamaForCausalLM" in `architectures`
2. Change `model_type` to "llama"
3. Remove the `sliding_window` field, and set `max_position_embeddings` to its value if there was one

So, for example, here's the config for Mistral-7B-v0.1:
```yml
{
  "architectures": [
    "MistralForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 14336,
  "max_position_embeddings": 32768,
  "model_type": "mistral",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 8,
  "rms_norm_eps": 1e-05,
  "rope_theta": 10000.0,
  "sliding_window": 4096,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.34.0.dev0",
  "use_cache": true,
  "vocab_size": 32000
}
```

If you edit the config to look like this:
```yml
{
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 14336,
  "max_position_embeddings": 4096,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 8,
  "rms_norm_eps": 1e-05,
  "rope_theta": 10000.0,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.34.0.dev0",
  "use_cache": true,
  "vocab_size": 32000
}
```

You have yourself a valid Llama model.
