### ISSUE TITLE
confuse about parameter t in slerp

### ISSUE THREAD

**Issue by zyh3826** [cg123/mergekit#70]
Hi @cg123, when using `slerp`, I was confused about the parameter `t` in `yaml` file
in [slerp.py](https://github.com/cg123/mergekit/blob/main/mergekit/merge_methods/slerp.py#L64), the parameter `t` is a `float` or `np.ndarray`, but I noticed in this [example](https://github.com/cg123/mergekit/blob/main/examples/gradient-slerp.yml), parameter `t `is a list, like:
```yaml
slices:
  - sources:
      - model: psmathur/orca_mini_v3_13b
        layer_range: [0, 40]
      - model: garage-bAInd/Platypus2-13B
        layer_range: [0, 40]
merge_method: slerp
base_model: psmathur/orca_mini_v3_13b
parameters:
  t:
    - filter: self_attn
      value: [0, 0.5, 0.3, 0.7, 1]
    - filter: mlp
      value: [1, 0.5, 0.7, 0.3, 0]
    - value: 0.5 # fallback for rest of tensors
dtype: float16
```
can you explain what's `t` in this `yaml` file mean? thanks a lot
