### ISSUE TITLE
Union tokenizer merging seems to break lazy tensor loading

### ISSUE THREAD

**Issue by brucethemoose** [cg123/mergekit#71]
I just freshly cloned mergekit. With the following config: 
```
models:
  - model: /home/alpha/Storage/Models/Raw/chargoddard_Yi-34B-200K-Llama
    # No parameters necessary for base model
  - model: /home/alpha/Storage/Models/Raw/Nous-Capybara-34B
    parameters:
      weight: 0.5
      density: 0.68
  - model: /home/alpha/Storage/Models/Raw/Weyaxi_Nous-Hermes-2-SUS-Chat-34B-Slerp
    parameters:
      weight: 0.5
      density: 0.45
merge_method: dare_ties
#tokenizer_source: union
base_model: /home/alpha/Storage/Models/Raw/chargoddard_Yi-34B-200K-Llama
parameters:
  int8_mask: true
dtype: bfloat16
```
And command: `mergekit-yaml --trust-remote-code /home/alpha/AI/mergeconfigs/custom-nosus.yml /home/alpha/Models/Raw/capymerge --cuda`

It uses very minimal RAM and 12GB of BRAM

But if I uncomment #tokenizer_source: union, it immediately uses up 64GB+ RAM and then OOMs my 24GB GPU. Beheaviour in CPU-only mode seems to be similar. 

I'm not sure how far back this bug goes. I've only just started using the union tokenizer merge.
