### ISSUE TITLE
RuntimeError:  Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again

### ISSUE THREAD

**Issue by Quang-elec44** [cg123/mergekit#85]
Hi, I am trying to merge two models following this [post](https://towardsdatascience.com/merge-large-language-models-with-mergekit-2118fb392b54). 
Here is my config:
```
yaml_config = """
slices:
  - sources:
    - model: vilm/vinallama-2.7b-chat
      layer_range: [0, 32]
  - sources:
    - model: vilm/vinallama-2.7b-chat
      layer_range: [0, 32]
merge_method: passthrough
dtype: bfloat16
"""
```
Here is the error log:
```
RuntimeError: 
            Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again: [{'model.layers.32.input_layernorm.weight', 'model.layers.0.input_layernorm.weight'}, {'model.layers.0.mlp.down_proj.weight' ...
A potential way to correctly save your model is to use `save_model`.
More information at https://huggingface.co/docs/safetensors/torch_shared_tensors
```

The author of this model successfully merged the 7B model using the same method (The model is [here](https://huggingface.co/qnguyen3/vinallama-12.5b-chat-franken/tree/main)). 
Am I doing anything wrong ?
