### ISSUE TITLE
Sane defaults for dare_ties merging?

### ISSUE THREAD

**Issue by brucethemoose** [cg123/mergekit#9]
Are weights that add up to ~1.2 a sane target? And whats a sane value for the Bernoulli density thing?

**Comment by cg123** [comment]
A total anywhere in the 0-1.2 range will almost certainly be fine. You can probably get a lot weirder than that, but I'm still experimenting myself.

The paper this method comes from (https://arxiv.org/abs/2311.03099) shows great results with a drop rate as high as 0.9, which would be a `density` value of 0.1. I haven't tried that low yet though. 0.3-0.5 have worked for me so far.

I'd be interested to hear if you get any fun results or run into any trouble with the code.

**Comment by brucethemoose** [comment]
Well for starters the install for the new branch doesn't quite work? I had to manually add the scripts and merge_methods folders into pip's install directory.

Mergekit doesn't like the Yi tokenizer, but that's fine, I can just use the llama one or copy it over. 

Also my first test merge also seems to be corrupt, and makes transformers error out with a bunch of strange CUDA asserts. A ties merge from the main branch 5 days ago worked fine. The config was:

```
models:
  - model: /home/alpha/Storage/Models/Raw/larryvrh_Yi-34B-200K-Llamafied
    # no parameters necessary for base model
  - model: /home/alpha/Storage/Models/Raw/migtissera_Tess-M-v1.2
    parameters:
      weight: 0.62
      density: 0.55
  - model: /home/alpha/Storage/Models/Raw/Nous-Capybara-34B
    parameters:
      weight: 0.56
      density: 0.55
merge_method: dare_ties
base_model: /home/alpha/Storage/Models/Raw/larryvrh_Yi-34B-200K-Llamafied
parameters:
  int8_mask: true
dtype: bfloat16
```

*shrug* My testing time is limited, but I will poke at it some more soon, lol.
